require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake 

AllCops:
  RubyInterpreters:
    - ruby
  TargetRubyVersion: 2.7.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

RSpec/ContextWording:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
